# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==icmp_rx_ram_8_256 || ORIG_REF_NAME==icmp_rx_ram_8_256} -quiet] -quiet

# IP: ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_rx_ram_8_2048 || ORIG_REF_NAME==udp_rx_ram_8_2048} -quiet] -quiet
