############## NET - IOSTANDARD ##################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
############## clock and reset define##################
create_clock -period 20.000 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN Y18 [get_ports sys_clk]
#################resetsetting###############################
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN F20 [get_ports rst_n]
############## key define##############################
set_property PACKAGE_PIN K14 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports key]
############# NET - IOSTANDARD ##################

set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[*]}]
set_property SLEW FAST [get_ports {rgmii_txd[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports e_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports e_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e_reset]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txctl]
set_property SLEW FAST [get_ports rgmii_txc]
set_property SLEW FAST [get_ports rgmii_txctl]

set_property PACKAGE_PIN J20 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN J17 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN M15 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN K19 [get_ports {rgmii_rxd[0]}]
set_property PACKAGE_PIN L20 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN L18 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN M20 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN J21 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN K17 [get_ports e_mdc]
set_property PACKAGE_PIN K16 [get_ports e_mdio]
set_property PACKAGE_PIN L15 [get_ports e_reset]
set_property PACKAGE_PIN K18 [get_ports rgmii_rxc]
set_property PACKAGE_PIN M21 [get_ports rgmii_rxctl]
set_property PACKAGE_PIN L14 [get_ports rgmii_txc]
set_property PACKAGE_PIN L19 [get_ports rgmii_txctl]
create_clock -period 8.000 -name rx_clk [get_ports rgmii_rxc]
#################AN5642 on J9#######################################
set_property PACKAGE_PIN B15 [get_ports cmos1_sda]
set_property PACKAGE_PIN B18 [get_ports {cmos1_db[9]}]
set_property PACKAGE_PIN B17 [get_ports {cmos1_db[8]}]
set_property PACKAGE_PIN A19 [get_ports cmos1_scl]
set_property PACKAGE_PIN A18 [get_ports {cmos1_db[5]}]
set_property PACKAGE_PIN C19 [get_ports {cmos1_db[3]}]
set_property PACKAGE_PIN C18 [get_ports {cmos1_db[4]}]
set_property PACKAGE_PIN A20 [get_ports {cmos1_db[6]}]
set_property PACKAGE_PIN B20 [get_ports {cmos1_db[0]}]
set_property PACKAGE_PIN C17 [get_ports {cmos1_db[7]}]
set_property PACKAGE_PIN D17 [get_ports {cmos1_db[1]}]
set_property PACKAGE_PIN D19 [get_ports {cmos1_db[2]}]
set_property PACKAGE_PIN E19 [get_ports cmos1_pclk]
set_property PACKAGE_PIN E18 [get_ports cmos1_href]
set_property PACKAGE_PIN F18 [get_ports cmos1_vsync]
set_property PACKAGE_PIN E17 [get_ports cmos1_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports cmos1_sda]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_scl]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_db[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_href]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_rst_n]

create_clock -period 11.904 [get_ports cmos1_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos1_pclk_IBUF]
set_input_delay -clock [get_clocks cmos1_pclk]  2.200 [get_ports {cmos1_db[*]}]
set_input_delay -clock [get_clocks cmos1_pclk]  2.200 [get_ports cmos1_href]
set_input_delay -clock [get_clocks cmos1_pclk] -min -add_delay 2.200 [get_ports cmos1_vsync]
set_input_delay -clock [get_clocks cmos1_pclk] -max -add_delay 4.000 [get_ports cmos1_vsync]

set_property PACKAGE_PIN D16 [get_ports {cmos2_db[9]}]
set_property PACKAGE_PIN E16 [get_ports {cmos2_sda}]
set_property PACKAGE_PIN F14 [get_ports {cmos2_db[6]}]
set_property PACKAGE_PIN F13 [get_ports {cmos2_scl}]
set_property PACKAGE_PIN E14 [get_ports {cmos2_db[7]}]
set_property PACKAGE_PIN E13 [get_ports {cmos2_db[2]}]
set_property PACKAGE_PIN D15 [get_ports {cmos2_href}]
set_property PACKAGE_PIN D14 [get_ports {cmos2_db[8]}]
set_property PACKAGE_PIN B13 [get_ports {cmos2_db[3]}]
set_property PACKAGE_PIN C13 [get_ports {cmos2_rst_n}]
set_property PACKAGE_PIN A14 [get_ports {cmos2_db[4]}]
set_property PACKAGE_PIN A13 [get_ports {cmos2_db[5]}]
set_property PACKAGE_PIN C15 [get_ports {cmos2_db[1]}]
set_property PACKAGE_PIN C14 [get_ports {cmos2_db[0]}]
set_property PACKAGE_PIN A16 [get_ports {cmos2_vsync}]
set_property PACKAGE_PIN A15 [get_ports {cmos2_pclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_scl}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_rst_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_db[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_pclk}]

create_clock -period 11.904 [get_ports cmos2_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos2_pclk_IBUF]
set_input_delay -clock [get_clocks cmos2_pclk] -min -add_delay 2.200 [get_ports {cmos2_db[*]}]
set_input_delay -clock [get_clocks cmos2_pclk] -max -add_delay 4.000 [get_ports {cmos2_db[*]}]
set_input_delay -clock [get_clocks cmos2_pclk] -min -add_delay 2.200 [get_ports cmos2_href]
set_input_delay -clock [get_clocks cmos2_pclk] -max -add_delay 4.000 [get_ports cmos2_href]
set_input_delay -clock [get_clocks cmos2_pclk] -min -add_delay 2.200 [get_ports cmos2_vsync]
set_input_delay -clock [get_clocks cmos2_pclk] -max -add_delay 4.000 [get_ports cmos2_vsync]

set_false_path -from [get_clocks cmos2_pclk] -to [get_clocks cmos1_pclk]
set_false_path -from [get_clocks sys_clk] -to [get_clocks -of_objects [get_pins rxd_clk_m0/inst/mmcm_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks sys_clk] -to [get_clocks cmos1_pclk]
set_false_path -from [get_clocks sys_clk] -to [get_clocks cmos2_pclk]
