# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sd_picture_hdmi.xdc

# IP: ip/ddr3/ddr3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3 || ORIG_REF_NAME==ddr3} -quiet] -quiet
