# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.cache/wt [current_project]
set_property parent.project_path D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/i2c_master/timescale.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/i2c_master/i2c_master_defines.v
}
set_property file_type "Verilog Header" [get_files D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/i2c_master/timescale.v]
set_property file_type "Verilog Header" [get_files D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/i2c_master/i2c_master_defines.v]
read_verilog -library xil_defaultlib {
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/arp_cache.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/rx/arp_rx.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/tx/arp_tx.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/camera_delay.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/cmos_select.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/crc.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/dpram.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/i2c_master/i2c_config.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/i2c_master/i2c_master_bit_ctrl.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/i2c_master/i2c_master_byte_ctrl.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/i2c_master/i2c_master_top.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/icmp_reply.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/rx/ip_rx.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/tx/ip_tx.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/tx/ip_tx_mode.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/lut_ov5640_rgb565_800_600.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/rx/mac_rx.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/rx/mac_rx_top.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/mac_test.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/mac_top.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/tx/mac_tx.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/tx/mac_tx_mode.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/tx/mac_tx_top.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/reset.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/rx/udp_rx.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/mac/tx/udp_tx.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/src/util_gmii_to_rgmii.v
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/video_ethernet.v
}
read_vhdl -library xil_defaultlib {
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/miim/miim_types.vhd
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/miim/utility.vhd
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/miim/miim.vhd
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/miim/miim_registers.vhd
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/miim/miim_control.vhd
  D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/miim/miim_top.vhd
}
read_ip -quiet D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/ip/camera_fifo/camera_fifo.xci
set_property used_in_implementation false [get_files -all d:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/ip/camera_fifo/camera_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/ip/camera_fifo/camera_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/sources_1/new/ip/camera_fifo/camera_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/constrs_1/new/video_ethernet.xdc
set_property used_in_implementation false [get_files D:/AX7035/24_video_ethernet/video_ethernet/video_ethernet.srcs/constrs_1/new/video_ethernet.xdc]


synth_design -top video_ethernet -part xc7a35tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef video_ethernet.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file video_ethernet_utilization_synth.rpt -pb video_ethernet_utilization_synth.pb"
