# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7035/demo_ax7035/22_USB_speed_test/usb_test/usb_test.srcs/sources_1/ip/ft_buf/ft_buf.xci
# IP: The module: 'ft_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/demo_ax7035/22_USB_speed_test/usb_test/usb_test.srcs/sources_1/ip/ft_buf/ft_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'ft_buf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/22_USB_speed_test/usb_test/usb_test.srcs/sources_1/ip/ft_buf/ft_buf_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ft_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/22_USB_speed_test/usb_test/usb_test.srcs/sources_1/ip/ft_buf/ft_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ft_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7035/demo_ax7035/22_USB_speed_test/usb_test/usb_test.srcs/sources_1/ip/ft_buf/ft_buf.xci
# IP: The module: 'ft_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/demo_ax7035/22_USB_speed_test/usb_test/usb_test.srcs/sources_1/ip/ft_buf/ft_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'ft_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/22_USB_speed_test/usb_test/usb_test.srcs/sources_1/ip/ft_buf/ft_buf_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ft_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/22_USB_speed_test/usb_test/usb_test.srcs/sources_1/ip/ft_buf/ft_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ft_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
