# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/ip/afifo_8i_32o_1024/afifo_8i_32o_1024.xci
# IP: The module: 'afifo_8i_32o_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/ip/afifo_8i_32o_1024/afifo_8i_32o_1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_8i_32o_1024'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/ip/afifo_8i_32o_1024/afifo_8i_32o_1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_8i_32o_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/ip/afifo_8i_32o_1024/afifo_8i_32o_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_8i_32o_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/ip/afifo_8i_32o_1024/afifo_8i_32o_1024.xci
# IP: The module: 'afifo_8i_32o_1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/ip/afifo_8i_32o_1024/afifo_8i_32o_1024.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_8i_32o_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/ip/afifo_8i_32o_1024/afifo_8i_32o_1024_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_8i_32o_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/ip/afifo_8i_32o_1024/afifo_8i_32o_1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_8i_32o_1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
