# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7035/demo_ax7035/sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M.xci
# IP: The module: 'clk_200M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/demo_ax7035/demo_ax7035/sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M.xci
# IP: The module: 'clk_200M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_hdmi/sd_picture_hdmi/sd_picture_hdmi.srcs/sources_1/ip/clk_200M/clk_200M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
