############## NET - IOSTANDARD ##################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
############## clock and reset define##################
create_clock -period 20.000 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN Y18 [get_ports sys_clk]
#################resetsetting###############################
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN F20 [get_ports rst_n]
############# NET - IOSTANDARD ##################

set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[*]}]
set_property SLEW FAST [get_ports {rgmii_txd[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports e_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports e_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e_reset]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txctl]
set_property SLEW FAST [get_ports rgmii_txc]
set_property SLEW FAST [get_ports rgmii_txctl]

set_property PACKAGE_PIN J20 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN J17 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN M15 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN K19 [get_ports {rgmii_rxd[0]}]
set_property PACKAGE_PIN L20 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN L18 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN M20 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN J21 [get_ports {rgmii_txd[0]}]
set_property PACKAGE_PIN K17 [get_ports e_mdc]
set_property PACKAGE_PIN K16 [get_ports e_mdio]
set_property PACKAGE_PIN L15 [get_ports e_reset]
set_property PACKAGE_PIN K18 [get_ports rgmii_rxc]
set_property PACKAGE_PIN M21 [get_ports rgmii_rxctl]
set_property PACKAGE_PIN L14 [get_ports rgmii_txc]
set_property PACKAGE_PIN L19 [get_ports rgmii_txctl]

create_clock -period 8.000 -name rx_clk [get_ports rgmii_rxc]

########AN706 ON AX7035 J9##################
set_property PACKAGE_PIN D16 [get_ports {ad7606_os[1]}]
set_property PACKAGE_PIN E16 [get_ports {ad7606_os[0]}]
set_property PACKAGE_PIN F14 [get_ports ad7606_convstab]
set_property PACKAGE_PIN F13 [get_ports {ad7606_os[2]}]
set_property PACKAGE_PIN E14 [get_ports ad7606_rd]
set_property PACKAGE_PIN E13 [get_ports ad7606_reset]
set_property PACKAGE_PIN D15 [get_ports ad7606_busy]
set_property PACKAGE_PIN D14 [get_ports ad7606_cs]
set_property PACKAGE_PIN C13 [get_ports ad7606_first_data]
set_property PACKAGE_PIN C15 [get_ports {ad7606_data[0]}]
set_property PACKAGE_PIN C14 [get_ports {ad7606_data[1]}]
set_property PACKAGE_PIN A16 [get_ports {ad7606_data[2]}]
set_property PACKAGE_PIN A15 [get_ports {ad7606_data[3]}]
set_property PACKAGE_PIN B16 [get_ports {ad7606_data[4]}]
set_property PACKAGE_PIN B15 [get_ports {ad7606_data[5]}]
set_property PACKAGE_PIN B18 [get_ports {ad7606_data[6]}]
set_property PACKAGE_PIN B17 [get_ports {ad7606_data[7]}]
set_property PACKAGE_PIN A19 [get_ports {ad7606_data[8]}]
set_property PACKAGE_PIN A18 [get_ports {ad7606_data[9]}]
set_property PACKAGE_PIN C19 [get_ports {ad7606_data[10]}]
set_property PACKAGE_PIN C18 [get_ports {ad7606_data[11]}]
set_property PACKAGE_PIN A20 [get_ports {ad7606_data[12]}]
set_property PACKAGE_PIN B20 [get_ports {ad7606_data[13]}]
set_property PACKAGE_PIN C17 [get_ports {ad7606_data[14]}]
set_property PACKAGE_PIN D17 [get_ports {ad7606_data[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_os[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_os[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_convstab]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_os[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_rd]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_busy]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_cs]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_first_data]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[15]}]

set_false_path -from [get_clocks clk_pll_i] -to [get_clocks clk_out1_video_pll]
set_false_path -from [get_clocks clk_out1_video_pll] -to [get_clocks clk_pll_i]

set_false_path -from [get_clocks clk_pll_i] -to [get_clocks clk_out1_rxd_clk]
set_false_path -from [get_clocks clk_out1_rxd_clk] -to [get_clocks clk_pll_i]

set_false_path -from [get_clocks clk_out1_video_pll] -to [get_clocks clk_out1_rxd_clk]
set_false_path -from [get_clocks clk_out1_rxd_clk] -to [get_clocks clk_out1_video_pll]

connect_debug_port u_ila_0/probe0 [get_nets [list {ethernet_reset/rst_cnt[0]} {ethernet_reset/rst_cnt[1]} {ethernet_reset/rst_cnt[2]} {ethernet_reset/rst_cnt[3]} {ethernet_reset/rst_cnt[4]} {ethernet_reset/rst_cnt[5]} {ethernet_reset/rst_cnt[6]} {ethernet_reset/rst_cnt[7]} {ethernet_reset/rst_cnt[8]} {ethernet_reset/rst_cnt[9]} {ethernet_reset/rst_cnt[10]} {ethernet_reset/rst_cnt[11]} {ethernet_reset/rst_cnt[12]} {ethernet_reset/rst_cnt[13]} {ethernet_reset/rst_cnt[14]} {ethernet_reset/rst_cnt[15]} {ethernet_reset/rst_cnt[16]} {ethernet_reset/rst_cnt[17]} {ethernet_reset/rst_cnt[18]} {ethernet_reset/rst_cnt[19]} {ethernet_reset/rst_cnt[20]} {ethernet_reset/rst_cnt[21]} {ethernet_reset/rst_cnt[22]} {ethernet_reset/rst_cnt[23]} {ethernet_reset/rst_cnt[24]} {ethernet_reset/rst_cnt[25]} {ethernet_reset/rst_cnt[26]} {ethernet_reset/rst_cnt[27]} {ethernet_reset/rst_cnt[28]} {ethernet_reset/rst_cnt[29]} {ethernet_reset/rst_cnt[30]} {ethernet_reset/rst_cnt[31]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {netchip_reset/rst_cnt[0]} {netchip_reset/rst_cnt[1]} {netchip_reset/rst_cnt[2]} {netchip_reset/rst_cnt[3]} {netchip_reset/rst_cnt[4]} {netchip_reset/rst_cnt[5]} {netchip_reset/rst_cnt[6]} {netchip_reset/rst_cnt[7]} {netchip_reset/rst_cnt[8]} {netchip_reset/rst_cnt[9]} {netchip_reset/rst_cnt[10]} {netchip_reset/rst_cnt[11]} {netchip_reset/rst_cnt[12]} {netchip_reset/rst_cnt[13]} {netchip_reset/rst_cnt[14]} {netchip_reset/rst_cnt[15]} {netchip_reset/rst_cnt[16]} {netchip_reset/rst_cnt[17]} {netchip_reset/rst_cnt[18]} {netchip_reset/rst_cnt[19]} {netchip_reset/rst_cnt[20]} {netchip_reset/rst_cnt[21]} {netchip_reset/rst_cnt[22]} {netchip_reset/rst_cnt[23]} {netchip_reset/rst_cnt[24]} {netchip_reset/rst_cnt[25]} {netchip_reset/rst_cnt[26]} {netchip_reset/rst_cnt[27]} {netchip_reset/rst_cnt[28]} {netchip_reset/rst_cnt[29]} {netchip_reset/rst_cnt[30]} {netchip_reset/rst_cnt[31]}]]

