# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/demo_ax7035/sd_card_audio/.Xil/Vivado-1128-ALINX000008-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tfgg484-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog {
      D:/demo_ax7035/sd_card_audio/.Xil/Vivado-1128-ALINX000008-PC/realtime/afifo_8i_32o_1024_stub.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/audio_tx.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/ax_debounce.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/i2c_master/i2c_config.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/i2c_master/timescale.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/i2c_master/i2c_master_defines.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/i2c_master/i2c_master_bit_ctrl.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/i2c_master/i2c_master_byte_ctrl.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/i2c_master/i2c_master_top.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/lut_wm8731.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/sd_card_audio.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/sd_card/sd_card_cmd.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/sd_card/sd_card_sec_read_write.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/sd_card/sd_card_top.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/sd_card/spi_master.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/wav_read.v
      D:/demo_ax7035/sd_card_audio/sd_card_audio.srcs/sources_1/src/top.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/demo_ax7035/sd_card_audio/.Xil/Vivado-1128-ALINX000008-PC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
