############## NET - IOSTANDARD ##################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
############## clock and reset define##################
create_clock -period 20 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_clk}]
set_property PACKAGE_PIN Y18 [get_ports {sys_clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]
set_property PACKAGE_PIN F20 [get_ports {rst_n}]
############## SD define##################
set_property IOSTANDARD LVCMOS33 [get_ports sd_dclk]
set_property PACKAGE_PIN N15 [get_ports sd_dclk]

set_property IOSTANDARD LVCMOS33 [get_ports sd_ncs]
set_property PACKAGE_PIN N13 [get_ports sd_ncs]

set_property IOSTANDARD LVCMOS33 [get_ports sd_mosi]
set_property PACKAGE_PIN P15 [get_ports sd_mosi]

set_property IOSTANDARD LVCMOS33 [get_ports sd_miso]
set_property PACKAGE_PIN P16 [get_ports sd_miso]
############## led define##################
set_property PACKAGE_PIN F19 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property PACKAGE_PIN E21 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]

set_property PACKAGE_PIN D20 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]

set_property PACKAGE_PIN C20 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
############## key define##################
set_property PACKAGE_PIN K14 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports key]
############## AN070 LCD on AX7035 J10##################
set_property PACKAGE_PIN N17 [get_ports {lcd_pwm}]
set_property PACKAGE_PIN T18 [get_ports {lcd_hs}]
set_property PACKAGE_PIN R18 [get_ports {lcd_vs}]
set_property PACKAGE_PIN U21 [get_ports {lcd_dclk}]
set_property PACKAGE_PIN T21 [get_ports {lcd_de}]
set_property PACKAGE_PIN V22 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN U22 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN V20 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN U20 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN W22 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN W21 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN Y22 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN Y21 [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN AA21 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN AA20 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN AB22 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN AB21 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN AB20 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN AA19 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN W20 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN W19 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN AB18 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN AA18 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN V19 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN V18 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN W17 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN V17 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN U18 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN U17 [get_ports {lcd_r[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_pwm}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[1]}]