# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/AX7325/exa_test_microblaze/test_hello_led_ddr/test_hello_led_ddr.srcs/sources_1/bd/mref/csi_rx_4lane/rxd_clk/rxd_clk.xci
# IP: The module: 'rxd_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AX7325/exa_test_microblaze/test_hello_led_ddr/test_hello_led_ddr.srcs/sources_1/bd/mref/csi_rx_4lane/rxd_clk/rxd_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/AX7325/exa_test_microblaze/test_hello_led_ddr/test_hello_led_ddr.srcs/sources_1/bd/mref/csi_rx_4lane/rxd_clk/rxd_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/AX7325/exa_test_microblaze/test_hello_led_ddr/test_hello_led_ddr.srcs/sources_1/bd/mref/csi_rx_4lane/rxd_clk/rxd_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/AX7325/exa_test_microblaze/test_hello_led_ddr/test_hello_led_ddr.srcs/sources_1/bd/mref/csi_rx_4lane/rxd_clk/rxd_clk.xci
# IP: The module: 'rxd_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AX7325/exa_test_microblaze/test_hello_led_ddr/test_hello_led_ddr.srcs/sources_1/bd/mref/csi_rx_4lane/rxd_clk/rxd_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/AX7325/exa_test_microblaze/test_hello_led_ddr/test_hello_led_ddr.srcs/sources_1/bd/mref/csi_rx_4lane/rxd_clk/rxd_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/AX7325/exa_test_microblaze/test_hello_led_ddr/test_hello_led_ddr.srcs/sources_1/bd/mref/csi_rx_4lane/rxd_clk/rxd_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
