# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ddr3_ov5640_an070.xdc

# IP: ip/ddr3/ddr3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3 || ORIG_REF_NAME==ddr3} -quiet] -quiet

# IP: ip/clk_200M/clk_200M.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_200M || ORIG_REF_NAME==clk_200M} -quiet] -quiet
