# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/AX7035/21_ad9226_ethernet/ad9226_ethernet/ad9226_ethernet.srcs/sources_1/ip/rxd_clk/rxd_clk.xci
# IP: The module: 'rxd_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AX7035/21_ad9226_ethernet/ad9226_ethernet/ad9226_ethernet.srcs/sources_1/ip/rxd_clk/rxd_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/AX7035/21_ad9226_ethernet/ad9226_ethernet/ad9226_ethernet.srcs/sources_1/ip/rxd_clk/rxd_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/AX7035/21_ad9226_ethernet/ad9226_ethernet/ad9226_ethernet.srcs/sources_1/ip/rxd_clk/rxd_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/AX7035/21_ad9226_ethernet/ad9226_ethernet/ad9226_ethernet.srcs/sources_1/ip/rxd_clk/rxd_clk.xci
# IP: The module: 'rxd_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AX7035/21_ad9226_ethernet/ad9226_ethernet/ad9226_ethernet.srcs/sources_1/ip/rxd_clk/rxd_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/AX7035/21_ad9226_ethernet/ad9226_ethernet/ad9226_ethernet.srcs/sources_1/ip/rxd_clk/rxd_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/AX7035/21_ad9226_ethernet/ad9226_ethernet/ad9226_ethernet.srcs/sources_1/ip/rxd_clk/rxd_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rxd_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
