# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.cache/wt [current_project]
set_property parent.project_path F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/aq_axi_master.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/ax_debounce.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/ax_pwm.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/bmp_read.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/video_define.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/color_bar.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/frame_fifo_read.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/frame_fifo_write.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/frame_read_write.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/sd_card_bmp.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/sd_card/sd_card_cmd.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/sd_card/sd_card_sec_read_write.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/sd_card/sd_card_top.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/sd_card/spi_master.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/video_timing_data.v
  F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/src/top.v
}
read_ip -quiet F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/ddr3/ddr3.xci
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3_ooc.xdc]

read_ip -quiet F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xci
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256_ooc.xdc]

read_ip -quiet F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xci
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_ooc.xdc]

read_ip -quiet F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/video_pll/video_pll.xci
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/video_pll/video_pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/video_pll/video_pll.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/video_pll/video_pll_late.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/video_pll/video_pll_ooc.xdc]

read_ip -quiet F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/sys_pll/sys_pll.xci
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/sys_pll/sys_pll_board.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/sys_pll/sys_pll.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/sys_pll/sys_pll_late.xdc]
set_property used_in_implementation false [get_files -all f:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/sys_pll/sys_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/constrs_1/new/sd_picture_lcd.xdc
set_property used_in_implementation false [get_files F:/demo_ax7035/demo_ax7035/13_3_sd_picture_lcd_an070/sd_picture_lcd_an070/sd_picture_lcd.srcs/constrs_1/new/sd_picture_lcd.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a35tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
