# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7035/demo_ax7035/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xci
# IP: The module: 'afifo_64i_32o_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7035/demo_ax7035/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xci
# IP: The module: 'afifo_64i_32o_128' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an070/sd_picture_lcd.srcs/sources_1/ip/afifo_64i_32o_128/afifo_64i_32o_128_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_64i_32o_128'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
