# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/demo_ax7035/demo_ax7035/sd_picture_lcd_an430/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xci
# IP: The module: 'afifo_32i_64o_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an430/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_64o_256'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an430/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_64o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an430/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_64o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/demo_ax7035/demo_ax7035/sd_picture_lcd_an430/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xci
# IP: The module: 'afifo_32i_64o_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an430/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_64o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an430/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_64o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/demo_ax7035/demo_ax7035/sd_picture_lcd_an430/sd_picture_lcd.srcs/sources_1/ip/afifo_32i_64o_256/afifo_32i_64o_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_32i_64o_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
