############## NET - IOSTANDARD ##################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design] 
set_property CONFIG_MODE SPIx4 [current_design] 
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design] 
############## clock and reset define##################
create_clock -period 20 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_clk}]
set_property PACKAGE_PIN Y18 [get_ports {sys_clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]
set_property PACKAGE_PIN F20 [get_ports {rst_n}]
set_property PACKAGE_PIN M13 [get_ports key1]
set_property IOSTANDARD LVCMOS33 [get_ports key1]

set_property PACKAGE_PIN K14 [get_ports key2]
set_property IOSTANDARD LVCMOS33 [get_ports key2]
############## AN070 LCD on AX7035 J10##################
set_property PACKAGE_PIN N17 [get_ports {lcd_pwm}]
set_property PACKAGE_PIN T18 [get_ports {lcd_hs}]
set_property PACKAGE_PIN R18 [get_ports {lcd_vs}]
set_property PACKAGE_PIN U21 [get_ports {lcd_dclk}]
set_property PACKAGE_PIN T21 [get_ports {lcd_de}]
set_property PACKAGE_PIN V22 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN U22 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN V20 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN U20 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN W22 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN W21 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN Y22 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN Y21 [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN AA21 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN AA20 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN AB22 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN AB21 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN AB20 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN AA19 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN W20 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN W19 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN AB18 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN AA18 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN V19 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN V18 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN W17 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN V17 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN U18 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN U17 [get_ports {lcd_r[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_pwm}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[1]}]
############## CMOS define J9##################
set_property PACKAGE_PIN A19 [get_ports cmos1_scl]
set_property PACKAGE_PIN B15 [get_ports cmos1_sda]
set_property PACKAGE_PIN E17 [get_ports cmos1_rst_n]
set_property PACKAGE_PIN E19 [get_ports cmos1_pclk]
set_property PACKAGE_PIN E18 [get_ports cmos1_href]
set_property PACKAGE_PIN F18 [get_ports cmos1_vsync]
set_property PACKAGE_PIN B18 [get_ports {cmos1_d[7]}]
set_property PACKAGE_PIN B17 [get_ports {cmos1_d[6]}]
set_property PACKAGE_PIN C17 [get_ports {cmos1_d[5]}]
set_property PACKAGE_PIN A20 [get_ports {cmos1_d[4]}]
set_property PACKAGE_PIN A18 [get_ports {cmos1_d[3]}]
set_property PACKAGE_PIN C18 [get_ports {cmos1_d[2]}]
set_property PACKAGE_PIN C19 [get_ports {cmos1_d[1]}]
set_property PACKAGE_PIN D19 [get_ports {cmos1_d[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cmos1_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_scl]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_href]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos1_rst_n]

set_property PACKAGE_PIN C13 [get_ports cmos2_rst_n]
set_property PACKAGE_PIN F13 [get_ports cmos2_scl]
set_property PACKAGE_PIN E16 [get_ports cmos2_sda]
set_property PACKAGE_PIN D15 [get_ports cmos2_href]
set_property PACKAGE_PIN A16 [get_ports cmos2_vsync]
set_property PACKAGE_PIN A15 [get_ports cmos2_pclk]
set_property PACKAGE_PIN D16 [get_ports {cmos2_d[7]}]
set_property PACKAGE_PIN D14 [get_ports {cmos2_d[6]}]
set_property PACKAGE_PIN E14 [get_ports {cmos2_d[5]}]
set_property PACKAGE_PIN F14 [get_ports {cmos2_d[4]}]
set_property PACKAGE_PIN A13 [get_ports {cmos2_d[3]}]
set_property PACKAGE_PIN A14 [get_ports {cmos2_d[2]}]
set_property PACKAGE_PIN B13 [get_ports {cmos2_d[1]}]
set_property PACKAGE_PIN E13 [get_ports {cmos2_d[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports cmos2_sda]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_scl]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_href]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cmos2_pclk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos1_pclk_IBUF]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos2_pclk_IBUF]

